create_clock -period 10.000 -name sysclk [get_ports sys_clk]
set_property PACKAGE_PIN L5 [get_ports sys_clk]
set_property PACKAGE_PIN H5 [get_ports sys_rest]
set_property PACKAGE_PIN V19 [get_ports {sig_led[3]}]
set_property PACKAGE_PIN U19 [get_ports {sig_led[2]}]
set_property PACKAGE_PIN U16 [get_ports {sig_led[1]}]
set_property PACKAGE_PIN T16 [get_ports {sig_led[0]}]

set_property PACKAGE_PIN H6 [get_ports key1_i]
set_property IOSTANDARD LVCMOS18 [get_ports key1_i]

set_property IOSTANDARD LVCMOS33 [get_ports {sig_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sig_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS18 [get_ports sys_rest]
set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
